/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThankYouRouteImport } from './routes/thank-you'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as MeetYourCoachRouteImport } from './routes/meet-your-coach'
import { Route as CoachingRouteImport } from './routes/coaching'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as AnchoredIn8RouteImport } from './routes/anchored-in-8'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnchoredIn8IndexRouteImport } from './routes/anchored-in-8/index'
import { Route as ThankYouRinseWashRepeatRouteImport } from './routes/thank-you/rinse-wash-repeat'
import { Route as ThankYouAnchoredJournalRouteImport } from './routes/thank-you/anchored-journal'
import { Route as AnchoredIn8PreviewRouteImport } from './routes/anchored-in-8/preview'
import { Route as AnchoredIn8OnboardingRouteImport } from './routes/anchored-in-8/onboarding'
import { Route as AnchoredIn8ConfirmationRouteImport } from './routes/anchored-in-8/confirmation'

const ThankYouRoute = ThankYouRouteImport.update({
  id: '/thank-you',
  path: '/thank-you',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetYourCoachRoute = MeetYourCoachRouteImport.update({
  id: '/meet-your-coach',
  path: '/meet-your-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingRoute = CoachingRouteImport.update({
  id: '/coaching',
  path: '/coaching',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchoredIn8Route = AnchoredIn8RouteImport.update({
  id: '/anchored-in-8',
  path: '/anchored-in-8',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnchoredIn8IndexRoute = AnchoredIn8IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnchoredIn8Route,
} as any)
const ThankYouRinseWashRepeatRoute = ThankYouRinseWashRepeatRouteImport.update({
  id: '/rinse-wash-repeat',
  path: '/rinse-wash-repeat',
  getParentRoute: () => ThankYouRoute,
} as any)
const ThankYouAnchoredJournalRoute = ThankYouAnchoredJournalRouteImport.update({
  id: '/anchored-journal',
  path: '/anchored-journal',
  getParentRoute: () => ThankYouRoute,
} as any)
const AnchoredIn8PreviewRoute = AnchoredIn8PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AnchoredIn8Route,
} as any)
const AnchoredIn8OnboardingRoute = AnchoredIn8OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AnchoredIn8Route,
} as any)
const AnchoredIn8ConfirmationRoute = AnchoredIn8ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => AnchoredIn8Route,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/anchored-in-8': typeof AnchoredIn8RouteWithChildren
  '/client-portal': typeof ClientPortalRoute
  '/coaching': typeof CoachingRoute
  '/meet-your-coach': typeof MeetYourCoachRoute
  '/results': typeof ResultsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/anchored-in-8/confirmation': typeof AnchoredIn8ConfirmationRoute
  '/anchored-in-8/onboarding': typeof AnchoredIn8OnboardingRoute
  '/anchored-in-8/preview': typeof AnchoredIn8PreviewRoute
  '/thank-you/anchored-journal': typeof ThankYouAnchoredJournalRoute
  '/thank-you/rinse-wash-repeat': typeof ThankYouRinseWashRepeatRoute
  '/anchored-in-8/': typeof AnchoredIn8IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-portal': typeof ClientPortalRoute
  '/coaching': typeof CoachingRoute
  '/meet-your-coach': typeof MeetYourCoachRoute
  '/results': typeof ResultsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/anchored-in-8/confirmation': typeof AnchoredIn8ConfirmationRoute
  '/anchored-in-8/onboarding': typeof AnchoredIn8OnboardingRoute
  '/anchored-in-8/preview': typeof AnchoredIn8PreviewRoute
  '/thank-you/anchored-journal': typeof ThankYouAnchoredJournalRoute
  '/thank-you/rinse-wash-repeat': typeof ThankYouRinseWashRepeatRoute
  '/anchored-in-8': typeof AnchoredIn8IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/anchored-in-8': typeof AnchoredIn8RouteWithChildren
  '/client-portal': typeof ClientPortalRoute
  '/coaching': typeof CoachingRoute
  '/meet-your-coach': typeof MeetYourCoachRoute
  '/results': typeof ResultsRoute
  '/shop': typeof ShopRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/thank-you': typeof ThankYouRouteWithChildren
  '/anchored-in-8/confirmation': typeof AnchoredIn8ConfirmationRoute
  '/anchored-in-8/onboarding': typeof AnchoredIn8OnboardingRoute
  '/anchored-in-8/preview': typeof AnchoredIn8PreviewRoute
  '/thank-you/anchored-journal': typeof ThankYouAnchoredJournalRoute
  '/thank-you/rinse-wash-repeat': typeof ThankYouRinseWashRepeatRoute
  '/anchored-in-8/': typeof AnchoredIn8IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/anchored-in-8'
    | '/client-portal'
    | '/coaching'
    | '/meet-your-coach'
    | '/results'
    | '/shop'
    | '/sitemap.xml'
    | '/thank-you'
    | '/anchored-in-8/confirmation'
    | '/anchored-in-8/onboarding'
    | '/anchored-in-8/preview'
    | '/thank-you/anchored-journal'
    | '/thank-you/rinse-wash-repeat'
    | '/anchored-in-8/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-portal'
    | '/coaching'
    | '/meet-your-coach'
    | '/results'
    | '/shop'
    | '/sitemap.xml'
    | '/thank-you'
    | '/anchored-in-8/confirmation'
    | '/anchored-in-8/onboarding'
    | '/anchored-in-8/preview'
    | '/thank-you/anchored-journal'
    | '/thank-you/rinse-wash-repeat'
    | '/anchored-in-8'
  id:
    | '__root__'
    | '/'
    | '/anchored-in-8'
    | '/client-portal'
    | '/coaching'
    | '/meet-your-coach'
    | '/results'
    | '/shop'
    | '/sitemap.xml'
    | '/thank-you'
    | '/anchored-in-8/confirmation'
    | '/anchored-in-8/onboarding'
    | '/anchored-in-8/preview'
    | '/thank-you/anchored-journal'
    | '/thank-you/rinse-wash-repeat'
    | '/anchored-in-8/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnchoredIn8Route: typeof AnchoredIn8RouteWithChildren
  ClientPortalRoute: typeof ClientPortalRoute
  CoachingRoute: typeof CoachingRoute
  MeetYourCoachRoute: typeof MeetYourCoachRoute
  ResultsRoute: typeof ResultsRoute
  ShopRoute: typeof ShopRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ThankYouRoute: typeof ThankYouRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/thank-you': {
      id: '/thank-you'
      path: '/thank-you'
      fullPath: '/thank-you'
      preLoaderRoute: typeof ThankYouRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-your-coach': {
      id: '/meet-your-coach'
      path: '/meet-your-coach'
      fullPath: '/meet-your-coach'
      preLoaderRoute: typeof MeetYourCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching': {
      id: '/coaching'
      path: '/coaching'
      fullPath: '/coaching'
      preLoaderRoute: typeof CoachingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchored-in-8': {
      id: '/anchored-in-8'
      path: '/anchored-in-8'
      fullPath: '/anchored-in-8'
      preLoaderRoute: typeof AnchoredIn8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anchored-in-8/': {
      id: '/anchored-in-8/'
      path: '/'
      fullPath: '/anchored-in-8/'
      preLoaderRoute: typeof AnchoredIn8IndexRouteImport
      parentRoute: typeof AnchoredIn8Route
    }
    '/thank-you/rinse-wash-repeat': {
      id: '/thank-you/rinse-wash-repeat'
      path: '/rinse-wash-repeat'
      fullPath: '/thank-you/rinse-wash-repeat'
      preLoaderRoute: typeof ThankYouRinseWashRepeatRouteImport
      parentRoute: typeof ThankYouRoute
    }
    '/thank-you/anchored-journal': {
      id: '/thank-you/anchored-journal'
      path: '/anchored-journal'
      fullPath: '/thank-you/anchored-journal'
      preLoaderRoute: typeof ThankYouAnchoredJournalRouteImport
      parentRoute: typeof ThankYouRoute
    }
    '/anchored-in-8/preview': {
      id: '/anchored-in-8/preview'
      path: '/preview'
      fullPath: '/anchored-in-8/preview'
      preLoaderRoute: typeof AnchoredIn8PreviewRouteImport
      parentRoute: typeof AnchoredIn8Route
    }
    '/anchored-in-8/onboarding': {
      id: '/anchored-in-8/onboarding'
      path: '/onboarding'
      fullPath: '/anchored-in-8/onboarding'
      preLoaderRoute: typeof AnchoredIn8OnboardingRouteImport
      parentRoute: typeof AnchoredIn8Route
    }
    '/anchored-in-8/confirmation': {
      id: '/anchored-in-8/confirmation'
      path: '/confirmation'
      fullPath: '/anchored-in-8/confirmation'
      preLoaderRoute: typeof AnchoredIn8ConfirmationRouteImport
      parentRoute: typeof AnchoredIn8Route
    }
  }
}

interface AnchoredIn8RouteChildren {
  AnchoredIn8ConfirmationRoute: typeof AnchoredIn8ConfirmationRoute
  AnchoredIn8OnboardingRoute: typeof AnchoredIn8OnboardingRoute
  AnchoredIn8PreviewRoute: typeof AnchoredIn8PreviewRoute
  AnchoredIn8IndexRoute: typeof AnchoredIn8IndexRoute
}

const AnchoredIn8RouteChildren: AnchoredIn8RouteChildren = {
  AnchoredIn8ConfirmationRoute: AnchoredIn8ConfirmationRoute,
  AnchoredIn8OnboardingRoute: AnchoredIn8OnboardingRoute,
  AnchoredIn8PreviewRoute: AnchoredIn8PreviewRoute,
  AnchoredIn8IndexRoute: AnchoredIn8IndexRoute,
}

const AnchoredIn8RouteWithChildren = AnchoredIn8Route._addFileChildren(
  AnchoredIn8RouteChildren,
)

interface ThankYouRouteChildren {
  ThankYouAnchoredJournalRoute: typeof ThankYouAnchoredJournalRoute
  ThankYouRinseWashRepeatRoute: typeof ThankYouRinseWashRepeatRoute
}

const ThankYouRouteChildren: ThankYouRouteChildren = {
  ThankYouAnchoredJournalRoute: ThankYouAnchoredJournalRoute,
  ThankYouRinseWashRepeatRoute: ThankYouRinseWashRepeatRoute,
}

const ThankYouRouteWithChildren = ThankYouRoute._addFileChildren(
  ThankYouRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnchoredIn8Route: AnchoredIn8RouteWithChildren,
  ClientPortalRoute: ClientPortalRoute,
  CoachingRoute: CoachingRoute,
  MeetYourCoachRoute: MeetYourCoachRoute,
  ResultsRoute: ResultsRoute,
  ShopRoute: ShopRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ThankYouRoute: ThankYouRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
